import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useEffect, useState } from "react";
import { ActivityIndicator, Modal, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { MAIN_TAB_BAR_HEIGHT } from "@/features/navigation/tabBarMetrics";
import { getLocationPreferences, updateLocationPreferences, type ApiLocationPreferences } from "@/services/api";
import { colors, fonts } from "@/theme/tokens";

const accuracyOptions = [{ value: "HIGH", label: "Alta precisão" }, { value: "BALANCED", label: "Economia de bateria" }, { value: "DEVICE", label: "Somente dispositivo" }] as const;
const frequencyOptions = [{ value: "REALTIME", label: "Tempo real" }, { value: "FIVE_MINUTES", label: "A cada 5 minutos" }, { value: "FIFTEEN_MINUTES", label: "A cada 15 minutos" }] as const;
const defaults: ApiLocationPreferences = { precise: true, accuracy: "HIGH", updateFreq: "REALTIME", shareWithFriends: true };

export default function FigmaLocationExperience() {
  const router = useRouter();
  const [preferences, setPreferences] = useState<ApiLocationPreferences | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [picker, setPicker] = useState<"accuracy" | "frequency" | null>(null);
  useEffect(() => { void load(); }, []);
  async function load() { setLoading(true); setError(null); try { setPreferences(await getLocationPreferences()); } catch { setError("Não foi possível carregar suas preferências de localização."); } finally { setLoading(false); } }
  async function patch(key: keyof ApiLocationPreferences, value: unknown) { if (!preferences) return; const previous = preferences; setPreferences({ ...preferences, [key]: value } as ApiLocationPreferences); try { setPreferences(await updateLocationPreferences({ [key]: value } as Partial<ApiLocationPreferences>)); } catch { setPreferences(previous); setError("Não foi possível salvar essa preferência."); } }
  if (loading && !preferences) return <View style={styles.root}><Header onBack={() => router.replace("/(main)/profile")} /><View style={styles.center}><ActivityIndicator color={colors.brand} /></View></View>;
  if (error && !preferences) return <View style={styles.root}><Header onBack={() => router.replace("/(main)/profile")} /><View style={styles.center}><Text style={styles.error}>{error}</Text><Pressable onPress={() => void load()}><Text style={styles.retry}>Tentar novamente</Text></Pressable></View></View>;
  const value = preferences ?? defaults;
  return <View style={styles.root}><Header onBack={() => router.replace("/(main)/profile")} /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    {error ? <Text style={styles.error}>{error}</Text> : null}
    <Section title="Permissões" />
    <ToggleRow label="Localização precisa" sub="Usa GPS para precisão máxima de posição" value={value.precise} onPress={() => void patch("precise", !value.precise)} />
    <ToggleRow label="Em segundo plano" sub="Atualiza quando o app está fechado · Em breve" value={false} disabled />
    <Section title="Preferências" />
    <SelectRow label="Precisão" value={accuracyOptions.find((x) => x.value === value.accuracy)?.label ?? "Alta precisão"} onPress={() => setPicker("accuracy")} />
    <SelectRow label="Frequência de atualização" value={frequencyOptions.find((x) => x.value === value.updateFreq)?.label ?? "Tempo real"} onPress={() => setPicker("frequency")} />
    <Section title="Compartilhamento" />
    <ToggleRow label="Compartilhar com amigos" sub="Amigos podem ver onde você está" value={value.shareWithFriends} onPress={() => void patch("shareWithFriends", !value.shareWithFriends)} />
    <ToggleRow label="Salvar histórico" sub="Guarda os lugares onde você esteve · Em breve" value={false} disabled />
    <View style={styles.info}><Text style={styles.infoText}>A localização é usada apenas para mostrar lugares e eventos próximos. Seus dados nunca são vendidos a terceiros.</Text></View>
  </ScrollView><Modal transparent visible={picker !== null} animationType="fade" onRequestClose={() => setPicker(null)}><Pressable style={styles.backdrop} onPress={() => setPicker(null)}><View style={styles.modal}><Text style={styles.modalTitle}>{picker === "accuracy" ? "Precisão" : "Frequência de atualização"}</Text>{(picker === "accuracy" ? accuracyOptions : frequencyOptions).map((option) => <Pressable key={option.value} style={styles.option} onPress={() => { if (picker === "accuracy") { if (option.value !== "DEVICE") void patch("accuracy", option.value); } else void patch("updateFreq", option.value); setPicker(null); }}><Text style={styles.optionText}>{option.label}</Text>{((picker === "accuracy" && option.value === value.accuracy) || (picker === "frequency" && option.value === value.updateFreq)) && <Ionicons name="checkmark" size={18} color={colors.brand} />}</Pressable>)}</View></Pressable></Modal></View>;
}
function Header({ onBack }: { onBack: () => void }) { return <View style={styles.header}><Pressable onPress={onBack} accessibilityRole="button" hitSlop={8}><Ionicons name="arrow-back" size={20} color={colors.brand} /></Pressable><Text style={styles.title}>Localização</Text></View>; }
function Section({ title }: { title: string }) { return <Text style={styles.section}>{title.toUpperCase()}</Text>; }
function ToggleRow({ label, sub, value, onPress, disabled = false }: { label: string; sub: string; value: boolean; onPress?: () => void; disabled?: boolean }) { return <View style={styles.row}><View style={styles.copy}><Text style={[styles.label, disabled && styles.disabled]}>{label}</Text><Text style={styles.sub}>{sub}</Text></View><Pressable accessibilityRole="switch" accessibilityState={{ checked: value, disabled }} disabled={disabled} onPress={onPress} style={[styles.toggle, { backgroundColor: value ? colors.brand : "#2A3340" }, disabled && styles.disabledToggle]}><View style={[styles.knob, { left: value ? 23 : 3, backgroundColor: value ? colors.background : colors.textMuted }]} /></Pressable></View>; }
function SelectRow({ label, value, onPress }: { label: string; value: string; onPress: () => void }) { return <Pressable onPress={onPress} style={styles.select}><Text style={styles.label}>{label}</Text><View style={styles.selectValue}><Text style={styles.value}>{value}</Text><Ionicons name="chevron-down" size={14} color={colors.textMuted} /></View></Pressable>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, header: { paddingTop: 14, paddingHorizontal: 20, paddingBottom: 12, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: "rgba(248,250,252,0.06)" }, title: { color: colors.text, fontFamily: fonts.display, fontSize: 18, fontWeight: "700" }, content: { paddingHorizontal: 20, paddingBottom: MAIN_TAB_BAR_HEIGHT + 24 }, section: { marginTop: 20, marginBottom: 8, color: colors.textMuted, fontFamily: fonts.semibold, fontSize: 11, letterSpacing: 1.1 }, row: { minHeight: 68, paddingVertical: 15, flexDirection: "row", alignItems: "center", gap: 16, borderBottomWidth: 1, borderBottomColor: "rgba(248,250,252,0.04)" }, copy: { flex: 1 }, label: { color: colors.text, fontFamily: fonts.medium, fontSize: 15, fontWeight: "500" }, disabled: { color: colors.textMuted }, sub: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 17, marginTop: 2 }, toggle: { width: 46, height: 26, borderRadius: 13 }, disabledToggle: { opacity: 0.55 }, knob: { position: "absolute", top: 3, width: 20, height: 20, borderRadius: 10 }, select: { minHeight: 54, paddingVertical: 14, flexDirection: "row", alignItems: "center", justifyContent: "space-between", borderBottomWidth: 1, borderBottomColor: "rgba(248,250,252,0.04)" }, selectValue: { flexDirection: "row", alignItems: "center", gap: 6 }, value: { color: colors.brand, fontFamily: fonts.regular, fontSize: 13 }, info: { marginTop: 20, paddingVertical: 14, paddingHorizontal: 16, backgroundColor: colors.surface, borderRadius: 14, borderWidth: 1, borderColor: "rgba(248,250,252,0.05)" }, infoText: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12, lineHeight: 19 }, center: { flex: 1, alignItems: "center", justifyContent: "center", padding: 20 }, error: { color: colors.danger, fontFamily: fonts.regular, textAlign: "center" }, retry: { color: colors.brand, marginTop: 12, fontFamily: fonts.semibold }, backdrop: { flex: 1, backgroundColor: "rgba(0,0,0,.65)", justifyContent: "flex-end" }, modal: { backgroundColor: colors.surface, borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 32 }, modalTitle: { color: colors.text, fontFamily: fonts.display, fontSize: 18, marginBottom: 8 }, option: { paddingVertical: 15, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1, borderBottomColor: "rgba(248,250,252,0.04)" }, optionText: { color: colors.text, fontFamily: fonts.regular, fontSize: 15 } });
