import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View, useWindowDimensions } from "react-native";
import { LiveMapContainer } from "@/components/home/LiveMapContainer";
import { MapBottomSheet } from "@/components/home/MapBottomSheet";
import { MapFilterChip } from "@/components/home/MapFilterChip";
import { MapLocationButton } from "@/components/home/MapLocationButton";
import { SearchThisAreaButton } from "@/components/home/SearchThisAreaButton";
import { SearchBar } from "@/components/home/SearchBar";
import { FigmaNearbyCard } from "@/components/home/FigmaNearbyCard";
import { FigmaNearbyPanel } from "@/components/home/FigmaNearbyPanel";
import { getEvents, getVenues, type ApiEvent, type ApiVenue } from "@/services/api";
import { useLocationStore } from "@/store/location-store";
import { colors, fonts } from "@/theme/tokens";
import { calculateDistance, formatDistance } from "@/utils/distance";
import type { NearbyDiscoveryItem } from "@/components/home/NearbyDiscoveryCard";

export default function FigmaHomeExperience() {
  const router = useRouter(); const { height } = useWindowDimensions(); const latitude = useLocationStore((s) => s.latitude); const longitude = useLocationStore((s) => s.longitude); const locationStatus = useLocationStore((s) => s.status);
  const [query, setQuery] = useState(""); const [time, setTime] = useState<"all" | "now" | "today">("all"); const [friends, setFriends] = useState(false); const [moved, setMoved] = useState(false); const [venues, setVenues] = useState<ApiVenue[]>([]); const [events, setEvents] = useState<ApiEvent[]>([]); const [selected, setSelected] = useState<ApiVenue | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [v, e] = await Promise.all([getVenues(), getEvents()]); setVenues(v); setEvents(e); } catch (err) { setError(err instanceof Error ? err.message : "Não foi possível carregar locais e eventos."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const items = useMemo<NearbyDiscoveryItem[]>(() => { const q = query.trim().toLowerCase(); const vs = venues.filter((v) => !q || `${v.name} ${v.category}`.toLowerCase().includes(q)).map((v) => { const d = latitude !== null && longitude !== null ? calculateDistance(latitude, longitude, Number(v.latitude), Number(v.longitude)) : null; return { id: v.id, kind: "venue" as const, title: v.name, category: v.category, distance: d === null ? v.distance : formatDistance(d), occupancy: v.occupancy > 70 ? "Cheio" : v.occupancy > 40 ? "Movimentado" : "Tranquilo", sort: d ?? Number.MAX_SAFE_INTEGER }; }); const es = events.filter((e) => !q || `${e.title} ${e.category}`.toLowerCase().includes(q)).map((e) => ({ id: e.id, kind: "event" as const, title: e.title, category: e.category, distance: e.distance, detail: `${e.date} · ${e.time}`, sort: Number.MAX_SAFE_INTEGER })); return [...vs, ...es].sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0)).slice(0, 4); }, [events, latitude, longitude, query, venues]);
  const mapHeight = Math.min(480, Math.max(320, Math.round(height * 0.57)));
  return <View testID="home-screen" style={styles.page}><ScrollView contentContainerStyle={styles.scroll} keyboardShouldPersistTaps="handled" showsVerticalScrollIndicator={false}><View style={styles.mapArea}><LiveMapContainer height={mapHeight} onLocationPress={() => setMoved(false)} onRegionChanged={() => setMoved(true)} onVenuePress={setSelected} selectedVenueId={selected?.id} venues={venues} /><View style={styles.overlay}><SearchBar onChangeText={setQuery} placeholder="Onde você quer ir?" value={query} /><ScrollView contentContainerStyle={styles.chips} horizontal showsHorizontalScrollIndicator={false}><MapFilterChip label="Agora" onPress={() => setTime((v) => v === "now" ? "all" : "now")} selected={time === "now"} /><MapFilterChip label="Hoje" onPress={() => setTime((v) => v === "today" ? "all" : "today")} selected={time === "today"} /><MapFilterChip label="Categorias" onPress={() => undefined} /><MapFilterChip label="Amigos" onPress={() => setFriends((v) => !v)} selected={friends} /></ScrollView></View><View style={styles.location}><MapLocationButton onPress={() => setMoved(false)} /></View>{moved ? <View style={styles.searchArea}><SearchThisAreaButton onPress={() => setMoved(false)} /></View> : null}{selected ? <MapBottomSheet distance={selected.distance} onClose={() => setSelected(null)} onViewDetails={() => router.push({ pathname: "/venue/[id]", params: { id: selected.id } })} venue={selected} /> : null}</View><FigmaNearbyPanel><View style={styles.cards}>{loading ? <View style={styles.loading}><ActivityIndicator color={colors.brand} /><Text style={styles.muted}>Encontrando o que há por aí…</Text></View> : error ? <Pressable onPress={() => void load()}><Text style={styles.error}>{error} · Tentar novamente</Text></Pressable> : items.length ? items.map((item) => <FigmaNearbyCard item={item} key={`${item.kind}-${item.id}`} onPress={() => item.kind === "venue" ? router.push({ pathname: "/venue/[id]", params: { id: item.id } }) : router.push({ pathname: "/event/[id]", params: { id: item.id } })} />) : <Text style={styles.muted}>Nada por aqui agora. Tente outra área.</Text>}</View>{locationStatus === "denied" ? <View style={styles.notice}><Ionicons color={colors.brand} name="location-outline" size={16} /><Text style={styles.muted}>Ative sua localização para ordenar por proximidade.</Text></View> : null}</FigmaNearbyPanel></ScrollView></View>;
}
const styles = StyleSheet.create({ page: { backgroundColor: colors.background, flex: 1 }, scroll: { paddingBottom: 20 }, mapArea: { position: "relative" }, overlay: { left: 16, position: "absolute", right: 16, top: 16, zIndex: 4 }, chips: { gap: 7, paddingLeft: 2, paddingTop: 10 }, location: { bottom: 18, position: "absolute", right: 16, zIndex: 5 }, searchArea: { position: "absolute", top: 165, width: "100%", zIndex: 5 }, cards: { gap: 8 }, loading: { alignItems: "center", flexDirection: "row", gap: 10, minHeight: 60 }, muted: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12 }, error: { color: colors.danger, fontFamily: fonts.regular, fontSize: 12, paddingVertical: 18 }, notice: { alignItems: "center", flexDirection: "row", gap: 8, marginTop: 12 } });
