import { LinearGradient } from "expo-linear-gradient";
import { useRouter } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Platform, Pressable, StyleSheet, Text, View } from "react-native";
import { EventSheet } from "@/components/home/figma/EventSheet";
import { FigmaDarkMapWeb } from "@/components/home/figma/FigmaDarkMap.web";
import { FigmaHomeFilters, type HomeFilter } from "@/components/home/figma/FigmaHomeFilters";
import { FigmaHomeSearch } from "@/components/home/figma/FigmaHomeSearch";
import { FigmaMapMarker } from "@/components/home/figma/FigmaMapMarker";
import { FigmaNearbyCard } from "@/components/home/figma/FigmaNearbyCard";
import { HomeLoadingOverlay, HomeNoLocationOverlay, HomeNoResultsOverlay, HomeOfflineOverlay } from "@/components/home/figma/HomeStateOverlays";
import { VenueSheet } from "@/components/home/figma/VenueSheet";
import { LiveMapContainer } from "@/components/home/LiveMapContainer";
import { MapLocationButton } from "@/components/home/MapLocationButton";
import { SearchThisAreaButton } from "@/components/home/SearchThisAreaButton";
import { getEvents, getVenues, type ApiEvent, type ApiVenue } from "@/services/api";
import { useLocationStore } from "@/store/location-store";
import { usePresenceStore } from "@/store/presence-store";
import { colors, fonts } from "@/theme/tokens";
import { calculateDistance, formatDistance } from "@/utils/distance";
import { getVenueAvailabilityState, getVenueOccupancyState } from "@/utils/venue-state";
import { normalizeVisualCategory } from "@/components/home/figma/visualCategories";
import type { NearbyDiscoveryItem } from "@/components/home/NearbyDiscoveryCard";

const slots = [[48,38],[60,52],[32,55],[72,45],[55,30],[42,65],[78,60],[25,40],[65,70],[50,72]] as const;
export default function FigmaProductionHome() {
  const router = useRouter(); const { latitude, longitude, status: locationStatus } = useLocationStore(); const friendLocations = usePresenceStore((state) => state.friendLocations); const presenceStatuses = usePresenceStore((state) => state.statuses);
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState<HomeFilter>("now"); const [moved, setMoved] = useState(false); const [venues, setVenues] = useState<ApiVenue[]>([]); const [events, setEvents] = useState<ApiEvent[]>([]); const [selectedVenue, setSelectedVenue] = useState<ApiVenue | null>(null); const [selectedEvent, setSelectedEvent] = useState<ApiEvent | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { const [v,e] = await Promise.all([getVenues(), getEvents()]); setVenues(v); setEvents(e); } catch (e) { setError(e instanceof Error ? e.message : "Não foi possível carregar a descoberta."); } finally { setLoading(false); } }, []); useEffect(() => { void load(); }, [load]);
  const nearbyFriends = Object.values(friendLocations).filter((friend) => presenceStatuses[friend.userId] === "ONLINE"); const friendsVisible = filter === "friends";
  const selectedVenueDistance = selectedVenue && latitude != null && longitude != null
    ? formatDistance(calculateDistance(latitude, longitude, Number(selectedVenue.latitude), Number(selectedVenue.longitude)))
    : selectedVenue?.distance;
  const items = useMemo<NearbyDiscoveryItem[]>(() => { const q = query.trim().toLowerCase(); const venueItems = venues.filter(v => !q || `${v.name} ${v.category}`.toLowerCase().includes(q)).map(v => { const d = latitude != null && longitude != null ? calculateDistance(latitude, longitude, Number(v.latitude), Number(v.longitude)) : null; return { id:v.id, kind:"venue" as const, title:v.name, category:v.category, distance:d == null ? v.distance : formatDistance(d), occupancy: getVenueOccupancyState(v).label, sort:d ?? Number.MAX_SAFE_INTEGER }; }); const eventItems = events.filter(e => { const matches = !q || `${e.title} ${e.category} ${e.venueName ?? ""}`.toLowerCase().includes(q); if (!matches) return false; if (filter === "now") return e.isLive; if (filter === "today") return new Date(e.date).toDateString() === new Date().toDateString(); return true; }).map(e => ({ id:e.id, kind:"event" as const, title:e.title, category:e.category, distance:e.distance, detail:`${e.date} · ${e.time}`, sort:Number.MAX_SAFE_INTEGER })); return [...venueItems, ...eventItems].sort((a,b)=>(a.sort ?? 0)-(b.sort ?? 0)).slice(0,4); }, [events, filter, latitude, longitude, query, venues]);
  const markerVenues = venues.slice(0, Math.min(10, venues.length)).map((venue, index) => <View key={venue.id} style={[styles.markerPosition, { left: `${slots[index][0]}%`, top: `${slots[index][1]}%` }]}><FigmaMapMarker category={normalizeVisualCategory(venue.category)} selected={selectedVenue?.id === venue.id} onPress={() => { setSelectedEvent(null); setSelectedVenue(venue); }} /></View>); const overflowCount = Math.max(0, venues.length - 9); if (overflowCount >= 2) { markerVenues.splice(9); markerVenues.push(<View key="cluster" style={[styles.markerPosition, { left: "50%", top: "72%" }]}><FigmaMapMarker category="cluster" clusterCount={overflowCount} /></View>); }
  const markerEvents = events.slice(0, 3).map((event, index) => event.venue ? <View key={`event-${event.id}`} style={[styles.markerPosition, { left: `${slots[index][0]}%`, top: `${slots[index][1]}%` }]}><FigmaMapMarker category="event" onPress={() => { setSelectedVenue(null); setSelectedEvent(event); }} /></View> : null);
  const sheetOpen = Boolean(selectedVenue || selectedEvent);
  return <View testID="home-screen" style={styles.root}><View style={styles.mapLayer}>{Platform.OS === "web" ? <FigmaDarkMapWeb friendsVisible={friendsVisible && nearbyFriends.length > 0} friendCount={nearbyFriends.length} userLocationAvailable={latitude != null && longitude != null}>{markerVenues}{markerEvents}</FigmaDarkMapWeb> : <LiveMapContainer height={480} venues={venues} selectedVenueId={selectedVenue?.id} onVenuePress={(v) => { setSelectedEvent(null); setSelectedVenue(v); }} onRegionChanged={() => setMoved(true)} onLocationPress={() => setMoved(false)} />}<LinearGradient colors={["rgba(11,13,15,.85)","transparent"]} style={styles.topGradient} /><LinearGradient colors={["transparent",colors.background]} style={styles.bottomGradient} /></View><View style={styles.searchLayer}><FigmaHomeSearch value={query} onChangeText={setQuery} /><FigmaHomeFilters value={filter} onChange={setFilter} /></View>{moved && <View style={styles.searchArea}><SearchThisAreaButton onPress={() => setMoved(false)} /></View>}<View style={[styles.location, sheetOpen && styles.locationSheet]}><MapLocationButton onPress={() => setMoved(false)} /></View>{friendsVisible && nearbyFriends.length > 0 && <View style={styles.friendIndicator}><View style={styles.friendDot} /><Text style={styles.friendText}>{nearbyFriends.length} {nearbyFriends.length === 1 ? "amigo" : "amigos"} por perto</Text></View>}<View style={styles.contentPanel}><Text style={styles.nearbyTitle}>Perto de você agora</Text>{locationStatus !== "granted" && <Text style={styles.locationHint}>Ative sua localização para ordenar por proximidade.</Text>}{loading ? <View style={styles.loading}><ActivityIndicator color={colors.brand} /><Text style={styles.meta}>Encontrando o que há por aí…</Text></View> : error ? <Pressable onPress={() => void load()}><Text style={styles.error}>{error} · Tentar novamente</Text></Pressable> : items.length === 0 ? <HomeNoResultsOverlay /> : <View style={styles.cards}>{items.map(item => <FigmaNearbyCard key={`${item.kind}-${item.id}`} item={item} onPress={() => item.kind === "venue" ? setSelectedVenue(venues.find(v => v.id === item.id) ?? null) : setSelectedEvent(events.find(e => e.id === item.id) ?? null)} />)}</View>}</View>{selectedVenue && <VenueSheet venue={selectedVenue} distance={selectedVenueDistance} onClose={() => setSelectedVenue(null)} onViewDetails={() => router.push({ pathname: "/venue/[id]", params: { id: selectedVenue.id } })} />}{selectedEvent && <EventSheet event={selectedEvent} onClose={() => setSelectedEvent(null)} onViewDetails={() => router.push({ pathname: "/event/[id]", params: { id: selectedEvent.id } })} />}{loading && <HomeLoadingOverlay />}{locationStatus === "denied" && !selectedVenue && !selectedEvent && <HomeNoLocationOverlay />}{error && /network|fetch|offline|conexão|conexao/i.test(error) && <HomeOfflineOverlay />}</View>;
}
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background, position: "relative" }, mapLayer: { position: "absolute", top: 0, left: 0, right: 0, height: 480, overflow: "hidden" }, topGradient: { position: "absolute", top: 0, left: 0, right: 0, height: 180 }, bottomGradient: { position: "absolute", bottom: 0, left: 0, right: 0, height: 80 }, markerPosition: { position: "absolute" }, searchLayer: { position: "absolute", top: 58, left: 16, right: 16, zIndex: 20 }, searchArea: { position: "absolute", top: 165, left: 0, right: 0, alignItems: "center", zIndex: 25 }, location: { position: "absolute", bottom: 406, right: 16, zIndex: 25 }, locationSheet: { bottom: 420 }, friendIndicator: { position: "absolute", top: 160, alignSelf: "center", flexDirection: "row", alignItems: "center", gap: 7, paddingVertical: 6, paddingHorizontal: 14, borderRadius: 20, backgroundColor: "rgba(21,25,29,.93)", borderWidth: 1, borderColor: "rgba(245,197,66,.3)", zIndex: 25 }, friendDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.brand }, friendText: { color: colors.brand, fontFamily: fonts.semibold, fontSize: 12 }, contentPanel: { position: "absolute", top: 450, left: 0, right: 0, bottom: 68, paddingHorizontal: 16, paddingBottom: 12, backgroundColor: "transparent", zIndex: 10 }, nearbyTitle: { color: colors.textMuted, fontFamily: fonts.semibold, fontSize: 12, letterSpacing: 1, marginBottom: 10, textTransform: "uppercase" }, locationHint: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12, marginBottom: 10 }, cards: { gap: 8 }, loading: { minHeight: 60, flexDirection: "row", alignItems: "center", gap: 10 }, meta: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12 }, error: { color: colors.danger, fontFamily: fonts.regular, fontSize: 12, paddingVertical: 16 } });
