import { Ionicons } from "@expo/vector-icons";
import { Image, Pressable, StyleSheet, Text, View } from "react-native";
import type { ApiEvent, ApiVenue } from "@/services/api";
import { colors, fonts, radii, shadows } from "@/theme/tokens";
type Props = { venue?: ApiVenue | null; event?: ApiEvent | null; distance?: string; onClose: () => void; onViewDetails: () => void };
export function MapBottomSheet({ venue, event, distance, onClose, onViewDetails }: Props) {
  const title = venue?.name ?? event?.title ?? "";
  const category = venue?.category ?? event?.category ?? "";
  const detail = venue ? (venue.occupancy > 70 ? "Cheio" : venue.occupancy > 40 ? "Movimentado" : "Tranquilo") : [event?.date, event?.time].filter(Boolean).join(" · ");
  const image = venue?.image ?? event?.image;
  const level = venue ? (venue.occupancy > 70 ? 3 : venue.occupancy > 40 ? 2 : 1) : 0;
  return <View accessibilityViewIsModal style={styles.sheet}><View style={styles.topRow}><View style={styles.grabber} /><Pressable accessibilityLabel="Fechar prévia" hitSlop={8} onPress={onClose}><Ionicons color={colors.textSecondary} name="close" size={20} /></Pressable></View>{image ? <Image accessibilityLabel={title} source={{ uri: image }} style={styles.image} /> : null}<View style={styles.content}><Text numberOfLines={1} style={styles.title}>{title}</Text><Text style={styles.meta}>{category}{distance ? ` · ${distance}` : ""}</Text><View style={styles.detailRow}><View style={styles.detailDot} /><Text style={styles.detail}>{detail}</Text></View>{venue ? <View style={styles.bars}>{[1, 2, 3].map((item) => <View key={item} style={[styles.bar, item <= level && styles.barActive]} />)}</View> : null}<Pressable accessibilityRole="button" onPress={onViewDetails} style={({ pressed }) => [styles.cta, pressed && styles.ctaPressed]}><Text style={styles.ctaText}>{venue ? "Ver local" : "Ver evento"}</Text><Ionicons color={colors.background} name="arrow-forward" size={17} /></Pressable></View></View>;
}
const styles = StyleSheet.create({ sheet: { backgroundColor: colors.surface, borderColor: colors.borderStrong, borderTopLeftRadius: radii.sheet, borderTopRightRadius: radii.sheet, borderWidth: 1, bottom: 0, left: 0, paddingBottom: 16, paddingTop: 8, position: "absolute", right: 0, ...shadows.floating }, topRow: { alignItems: "center", flexDirection: "row", height: 24, justifyContent: "flex-end", paddingHorizontal: 16 }, grabber: { backgroundColor: "#2A3340", borderRadius: 2, height: 4, left: "50%", marginLeft: -18, position: "absolute", width: 36 }, image: { borderRadius: 16, height: 120, marginHorizontal: 16, marginTop: 4, width: "auto" }, content: { paddingHorizontal: 20 }, title: { color: colors.text, fontFamily: fonts.bold, fontSize: 20, marginTop: 12 }, meta: { color: colors.textSecondary, fontFamily: fonts.regular, fontSize: 13, marginTop: 3 }, detailRow: { alignItems: "center", flexDirection: "row", gap: 6, marginTop: 9 }, detailDot: { backgroundColor: colors.brand, borderRadius: 3, height: 6, width: 6 }, detail: { color: colors.brand, fontFamily: fonts.semibold, fontSize: 12 }, bars: { flexDirection: "row", gap: 2, marginTop: 5 }, bar: { backgroundColor: "#2A3340", borderRadius: 2, height: 4, width: 10 }, barActive: { backgroundColor: colors.brand }, cta: { alignItems: "center", backgroundColor: colors.brand, borderRadius: 14, flexDirection: "row", gap: 7, justifyContent: "center", marginTop: 14, minHeight: 48 }, ctaText: { color: colors.background, fontFamily: fonts.bold, fontSize: 14 }, ctaPressed: { backgroundColor: colors.brandPressed } });
