import { Pressable, StyleSheet, Text, View } from "react-native";
import { MAIN_TAB_BAR_HEIGHT } from "@/features/navigation/tabBarMetrics";
import type { NearbyPlace } from "@/services/api/resources/discovery";
import { colors, fonts } from "@/theme/tokens";

export function ExternalPlaceSheet({ place, onClose }: { place: NearbyPlace; onClose: () => void }) {
  return <View style={styles.overlay}><Pressable accessibilityRole="button" accessibilityLabel="Fechar local" onPress={onClose} style={styles.backdrop} /><View testID="external-place-sheet" style={styles.sheet}><View style={styles.handle} /><View style={styles.header}><View style={styles.copy}><Text numberOfLines={2} style={styles.title}>{place.name}</Text><Text style={styles.category}>{place.category} · {(place.distanceMeters / 1000).toFixed(1)} km</Text><Text style={styles.address}>{place.address ?? place.locality ?? "Endereço não disponível"}</Text><Text style={styles.source}>Descoberto via Foursquare</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Fechar local" onPress={onClose} style={styles.close}><Text style={styles.closeText}>Fechar</Text></Pressable></View></View></View>;
}

const styles = StyleSheet.create({ overlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: MAIN_TAB_BAR_HEIGHT, justifyContent: "flex-end", zIndex: 40 }, backdrop: { ...StyleSheet.absoluteFill, backgroundColor: "rgba(11,13,15,0.42)" }, sheet: { paddingHorizontal: 20, paddingBottom: 20, paddingTop: 8, backgroundColor: colors.surface, borderTopLeftRadius: 24, borderTopRightRadius: 24, borderWidth: 1, borderBottomWidth: 0, borderColor: colors.border, zIndex: 2 }, handle: { alignSelf: "center", width: 36, height: 4, borderRadius: 2, backgroundColor: "#2A3340", marginBottom: 10, marginTop: 5 }, header: { flexDirection: "row", gap: 12 }, copy: { flex: 1 }, title: { color: colors.text, fontFamily: fonts.bold, fontSize: 18 }, category: { color: colors.brand, fontFamily: fonts.semibold, fontSize: 12, marginTop: 4 }, address: { color: colors.textSecondary, fontFamily: fonts.regular, fontSize: 13, marginTop: 8 }, source: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 11, marginTop: 6 }, close: { alignSelf: "flex-start", paddingHorizontal: 10, paddingVertical: 6 }, closeText: { color: colors.textMuted, fontFamily: fonts.semibold, fontSize: 12 } });
