import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Image, Pressable, RefreshControl, StyleSheet, Text, View } from "react-native";
import { useFriendsQuery, useFriendRequestsQuery, useFriendMutation, type Friend, type FriendRequest } from "@/services/api/resources/friends";
import { getPresence } from "@/services/socket";
import { usePresenceStore } from "@/store/presence-store";
import { colors, fonts } from "@/theme/tokens";

type Tab = "saindo" | "todos";

export default function FigmaFriendsExperience() {
  const statuses = usePresenceStore((state) => state.statuses);
  const locations = usePresenceStore((state) => state.friendLocations);
  const friendsQuery = useFriendsQuery({ page: 1, limit: 100 });
  const requestsQuery = useFriendRequestsQuery({ page: 1, limit: 100 });
  const acceptMutation = useFriendMutation("accept");
  const rejectMutation = useFriendMutation("reject");
  const friends = friendsQuery.data?.items ?? [];
  const requests = (requestsQuery.data?.items ?? []).filter((item) => item.status === "PENDING");
  const loading = friendsQuery.isLoading || requestsQuery.isLoading;
  const error = friendsQuery.error || requestsQuery.error;
  const [refreshing, setRefreshing] = useState(false);
  const [tab, setTab] = useState<Tab>("saindo");
  const load = async () => { setRefreshing(true); await Promise.all([friendsQuery.refetch(), requestsQuery.refetch()]); setRefreshing(false); };
  const online = useMemo(() => friends.filter((friend) => (statuses[friend.id] ?? friend.status) === "ONLINE"), [friends, statuses]);
  const visible = useMemo(() => friends.filter((friend) => tab === "todos" || (statuses[friend.id] ?? friend.status) === "ONLINE").sort((a, b) => a.name.localeCompare(b.name, "pt-BR")), [friends, statuses, tab]);
  const respond = (request: FriendRequest, action: "accept" | "reject") => { (action === "accept" ? acceptMutation : rejectMutation).mutate(request.id); };
  return <View style={styles.page}><FlatList data={visible} keyExtractor={(item) => item.id} contentContainerStyle={styles.list} refreshControl={<RefreshControl refreshing={refreshing} tintColor={colors.brand} onRefresh={() => { void load(); }} />} ListHeaderComponent={<><View style={styles.header}><Text style={styles.heading}>Amigos</Text><Pressable onPress={() => router.push("/(main)/invites")} style={styles.add} accessibilityRole="button" accessibilityLabel="Adicionar amigo"><Ionicons name="person-add-outline" size={18} color={colors.brand} /></Pressable></View><View style={styles.tabs}>{(["saindo", "todos"] as Tab[]).map((item) => <Pressable key={item} onPress={() => setTab(item)} style={[styles.tab, tab === item && styles.tabActive]}><Text style={[styles.tabText, tab === item && styles.tabTextActive]}>{item === "saindo" ? `🔥 Saindo agora (${online.length})` : `Todos (${friends.length})`}</Text></Pressable>)}</View>{requests.length > 0 && <View style={styles.requests}><Text style={styles.sectionLabel}>SOLICITAÇÕES</Text>{requests.map((request) => <View key={request.id} style={styles.request}><Avatar user={request.requester} size={46} /><View style={styles.requestCopy}><Text style={styles.name}>{request.requester?.name ?? "Usuário"}</Text><Text style={styles.muted}>quer fazer parte da sua rede</Text><View style={styles.requestActions}><Pressable onPress={() => void respond(request, "accept")} style={styles.accept}><Text style={styles.acceptText}>Aceitar</Text></Pressable><Pressable onPress={() => void respond(request, "reject")} style={styles.reject}><Text style={styles.rejectText}>Recusar</Text></Pressable></View></View></View>)}</View>}{error && <Text style={styles.error}>{error instanceof Error ? error.message : "Não foi possível carregar seus amigos."}</Text>}{loading && <View style={styles.loading}><ActivityIndicator color={colors.brand} /><Text style={styles.muted}>Carregando amigos…</Text></View>}</>} ListEmptyComponent={!loading ? <View style={styles.empty}><Ionicons name="people-outline" size={30} color={colors.brand} /><Text style={styles.emptyTitle}>Sua rede começa aqui</Text><Text style={styles.muted}>Quando suas solicitações forem aceitas, as pessoas aparecerão aqui.</Text></View> : null} renderItem={({ item }) => <FriendRow friend={item} online={(statuses[item.id] ?? item.status) === "ONLINE"} nearby={Boolean(locations[item.id])} />} showsVerticalScrollIndicator={false} /></View>;
}
function Avatar({ user, size }: { user?: { name?: string; avatar?: string | null } | null; size: number }) { return user?.avatar ? <Image source={{ uri: user.avatar }} style={{ width: size, height: size, borderRadius: size / 2 }} /> : <View style={[styles.avatarFallback, { width: size, height: size, borderRadius: size / 2 }]}><Text style={styles.avatarText}>{(user?.name ?? "?").charAt(0).toUpperCase()}</Text></View>; }
function FriendRow({ friend, online, nearby }: { friend: Friend; online: boolean; nearby: boolean }) { const openFriend = () => router.push({ pathname: "/(main)/friend/[id]", params: { id: friend.id } }); const openChat = () => router.push({ pathname: "/(main)/chat/[id]", params: { id: friend.id } }); return <View style={styles.friend}><Pressable accessibilityRole="button" accessibilityLabel={`Abrir perfil de ${friend.name}`} onPress={openFriend} style={{ flex: 1, minWidth: 0, flexDirection: "row", alignItems: "center", gap: 12 }}><View style={styles.avatarWrap}><Avatar user={friend} size={46} /><View style={[styles.presence, !online && styles.offline]} /></View><View style={styles.friendCopy}><Text numberOfLines={1} style={styles.name}>{friend.name}</Text><Text style={[styles.status, online && styles.online]}>{online ? "Saindo agora" : "Em casa"}{nearby ? " · por perto" : ""}</Text></View></Pressable><Pressable onPress={openChat} style={styles.chat} accessibilityRole="button" accessibilityLabel={`Conversar com ${friend.name}`}><Ionicons name="chatbubble-outline" size={16} color={colors.textMuted} /></Pressable></View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, list: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 110 }, header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 16 }, heading: { color: colors.text, fontFamily: fonts.display, fontSize: 22 }, add: { width: 36, height: 36, borderRadius: 18, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" }, tabs: { flexDirection: "row", backgroundColor: colors.surface, borderRadius: 14, padding: 4, marginBottom: 20 }, tab: { flex: 1, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center" }, tabActive: { backgroundColor: colors.elevated }, tabText: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 13 }, tabTextActive: { color: colors.text, fontFamily: fonts.semibold }, requests: { backgroundColor: colors.surface, borderRadius: 16, padding: 12, marginBottom: 16 }, sectionLabel: { color: colors.textMuted, fontFamily: fonts.bold, fontSize: 10, letterSpacing: 1, marginBottom: 8 }, request: { flexDirection: "row", gap: 10, paddingVertical: 8 }, requestCopy: { flex: 1 }, requestActions: { flexDirection: "row", gap: 8, marginTop: 8 }, accept: { backgroundColor: colors.brand, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 7 }, acceptText: { color: colors.background, fontFamily: fonts.bold, fontSize: 11 }, reject: { backgroundColor: colors.elevated, borderRadius: 10, paddingHorizontal: 12, paddingVertical: 7 }, rejectText: { color: colors.textSecondary, fontFamily: fonts.semibold, fontSize: 11 }, friend: { minHeight: 70, backgroundColor: colors.surface, borderRadius: 16, padding: 12, marginBottom: 10, flexDirection: "row", alignItems: "center", gap: 12 }, avatarWrap: { position: "relative" }, avatarFallback: { backgroundColor: colors.brandSecondary, alignItems: "center", justifyContent: "center" }, avatarText: { color: colors.text, fontFamily: fonts.bold, fontSize: 17 }, presence: { position: "absolute", right: 0, bottom: 0, width: 10, height: 10, borderRadius: 5, backgroundColor: colors.success, borderWidth: 2, borderColor: colors.surface }, offline: { backgroundColor: colors.textMuted }, friendCopy: { flex: 1 }, name: { color: colors.text, fontFamily: fonts.semibold, fontSize: 15 }, status: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12, marginTop: 3 }, online: { color: colors.success }, chat: { width: 34, height: 34, borderRadius: 17, borderWidth: 1, borderColor: colors.border, alignItems: "center", justifyContent: "center" }, loading: { alignItems: "center", gap: 10, paddingVertical: 30 }, muted: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12 }, error: { color: colors.danger, fontFamily: fonts.regular, fontSize: 12, marginBottom: 12 }, empty: { alignItems: "center", paddingVertical: 48, gap: 10 }, emptyTitle: { color: colors.text, fontFamily: fonts.bold, fontSize: 16 }, });
