import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const checks = [];
const assert = (name, condition) => checks.push({ name, ok: Boolean(condition) });

const tabs = read("src/features/navigation/MainTabsExperience.tsx");
const rootLayout = read("src/app/_layout.tsx");
const chat = read("src/features/chat/ChatInboxExperience.tsx");
const createGroup = read("src/features/groups/CreateGroupExperience.tsx");
const profile = read("src/features/profile/FigmaProfileExperience.tsx");
const friends = read("src/features/social/FigmaFriendsExperience.tsx");
const explore = read("src/features/discovery/FigmaExploreExperience.tsx");
const cover = read("src/features/profile/FigmaProfileExperience.tsx");
const notificationCenter = read("src/features/notifications/NotificationCenterExperience.tsx");
const invitesRoute = read("src/app/(main)/invites.tsx");
const venueState = read("src/utils/venue-state.ts");const groupDetail = read("src/features/groups/GroupDetailExperience.tsx");
const inviteToGroup = read("src/features/groups/InviteToGroupExperience.tsx");
const groupChat = read("src/features/groups/GroupChatExperience.tsx");
const chatInbox = read("src/features/chat/ChatInboxExperience.tsx");
const directChat = read("src/features/chat/DirectChatExperience.tsx");
const messagesResource = read("src/services/api/resources/messages.ts");
const confirmDelete = read("src/features/chat/confirmDelete.ts");
const contextActions = read("src/features/chat/MessageContextActions.tsx");
const socketService = read("src/services/socket.ts");
const apiClient = read("src/services/api/client.ts");
const authService = read("src/services/api/auth.ts");
const home = read("src/features/home/FigmaProductionHome.tsx");
const venuesResource = read("src/services/api/resources/venues.ts");
const eventsResource = read("src/services/api/resources/events.ts");
const locationService = read("src/components/LocationTracker.tsx");
const liveMapContainer = read("src/components/home/LiveMapContainer.tsx");
const packageJson = read("package.json");
const distance = read("src/utils/distance.ts");
const discoveryResource = read("src/services/api/resources/discovery.ts");

assert("six primary tabs", ["home", "explore", "events", "friends", "chat", "profile"].every((key) => tabs.includes(`name="${key}"`)));
assert("groups is hidden from primary tab bar", /name="groups" options=\{\{ href: null \}\}/.test(tabs));
assert("chat plus opens create group", chat.includes("/(main)/group/create"));
assert("create group back targets chat", createGroup.includes('router.replace("/(main)/chat")'));
assert("profile Groups row is not rendered", profile.includes('if (label === "Grupos") return null'));
assert("profile cover is local", cover.includes("assets/images/profile-cover.jpg") && !cover.includes("images.unsplash.com"));
assert("friends row has sibling actions", friends.includes("<View style={styles.friend}") && friends.includes("Abrir perfil de"));
assert("explore title remains 22px", /title:\s*\{[^}]*fontSize:\s*22/.test(explore));
assert("notification center is not a primary tab", !/name="notification-center"/.test(tabs));assert("GroupDetail avoids legacy stores", !groupDetail.includes("useGroupStore") && !groupDetail.includes("useInviteStore"));
assert("Home uses real discovery resources", home.includes("useVenuesQuery") && home.includes("useEventsQuery") && venuesResource.includes("listVenues") && eventsResource.includes("listEvents"));
assert("Home location has safe fallback", home.includes('locationStatus !== "granted"') && /setStatus\(\s*"denied"/.test(locationService));
const realMapWeb = read("src/components/home/RealMap.web.tsx");
const realMapNative = read("src/components/home/RealMap.native.tsx");
const realMapContainerWeb = read("src/components/home/RealMapContainer.web.tsx");
const realMapContainerNative = read("src/components/home/RealMapContainer.native.tsx");
const externalPlaceSheet = read("src/components/home/ExternalPlaceSheet.tsx");
assert("Home map keeps Web and Native split", home.includes("RealMapContainer") && realMapWeb.includes("maplibre-gl") && realMapNative.includes("LiveMap.native") && realMapContainerWeb.includes("RealMap.web") && realMapContainerNative.includes("RealMap.native"));
assert("Home Web map uses OpenFreeMap dark vector style and coordinates", realMapWeb.includes("tiles.openfreemap.org/styles/dark") && realMapWeb.includes("venue.latitude") && realMapWeb.includes("event.venue?.latitude"));
assert("Home Web map hides default navigation control", !realMapWeb.includes("NavigationControl") && !realMapWeb.includes("addControl"));
assert("Home Web attribution stays compact and available", realMapWeb.includes("attributionControl: { compact: true }") && !realMapWeb.includes("attributionControl: false") && read("src/components/home/real-map-attribution.css").includes(".maplibregl-ctrl-attrib"));
assert("Home map recenter is wired", home.includes("recenterKey") && realMapWeb.includes("easeTo") && read("src/components/home/LiveMap.native.tsx").includes("recenterKey"));
assert("MapLibre v5 is used without worker sync workaround", /\"maplibre-gl\": \"\^5\./.test(packageJson) && !realMapWeb.includes("setWorkerUrl") && !packageJson.includes("sync-maplibre-worker"));
assert("Map loading has no permanent fake fallback", realMapWeb.includes("map.loaded()") && realMapWeb.includes("mapError") && !realMapWeb.includes("FigmaDarkMap"));
assert("Home map initial camera fits points once", realMapWeb.includes("initialCameraDone") && realMapWeb.includes("fitBounds") && realMapWeb.includes("maxZoom"));
assert("Home map recenter remains user-only", realMapWeb.includes("validPoint(latitude, longitude)") && realMapWeb.includes("easeTo({ center: point"));
assert("Home markers stay geographic", realMapWeb.includes("setLngLat(point)") && realMapWeb.includes("venue.latitude") && realMapWeb.includes("event.venue?.latitude"));
assert("Nearby radius has one shared source", distance.includes("NEARBY_RADIUS_KM") && distance.includes("isWithinNearbyRadius") && home.includes("isWithinNearbyRadius"));
assert("Nearby radius is five kilometers", /NEARBY_RADIUS_KM\s*=\s*5/.test(distance));
assert("Home map and list use nearby collections", home.includes("nearbyVenues") && home.includes("nearbyEvents") && home.includes("mapVenues") && home.includes("mapEvents"));
assert("Nearby list includes every in-radius entity", !home.includes(".slice(0,4)"));
assert("Global search remains unrestricted", home.includes("const sourceVenues = q ? venues :") && home.includes("const sourceEvents = q ? events :") && home.includes("const q = query.trim().toLowerCase()"));
assert("Map and list share category-filtered collections", home.includes("filteredVenues") && home.includes("filteredEvents") && home.includes("filteredExternalPlaces") && home.includes("externalPlaces={filteredExternalPlaces}"));
assert("Nearby items are sorted by distance", home.includes("sort: (a, b) => (a.sort ?? 0) - (b.sort ?? 0)") || home.includes("sort((a, b) => (a.sort ?? 0) - (b.sort ?? 0))"));
assert("External selection is single-state and preview-only", home.includes("selectedExternal") && home.includes("setSelectedExternal(place)") && externalPlaceSheet.includes("ExternalPlaceSheet"));
assert("External places do not expose fake occupancy or rating", !externalPlaceSheet.includes("rating") && !externalPlaceSheet.includes("occupancy"));
assert("Internal venue favorites stay backend-backed", home.includes("useFavoritesQuery") && home.includes("useFavoriteMutation") && home.includes("favoriteVenueIds"));
assert("External places have no favorite action", !externalPlaceSheet.includes("favorite") && !externalPlaceSheet.includes("heart"));
assert("Nearby empty state respects active filter/search", home.includes("Nenhum resultado") && home.includes("selectedCategory") && home.includes("Nenhum ${selectedCategory.toLowerCase()} encontrado"));
assert("Home distinguishes initial loading from settled empty", home.includes("initialLoading") && home.includes("locationResolving") && home.includes("items.length === 0"));
assert("Background refetch keeps existing content", home.includes("venuesQuery.isFetching") && home.includes("eventsQuery.isFetching") && home.includes("discoveryQuery.isFetching") && home.includes("initialLoading"));
assert("Partial source failure preserves healthy data", home.includes("venuesQuery.error && venues.length === 0") && home.includes("eventsQuery.error && events.length === 0"));
assert("Map does not apply a divergent radius", !realMapWeb.includes("<= 50") && !realMapWeb.includes("slice(0, 20)"));
assert("Nearby radius boundary is inclusive", distance.includes("distanceInMeters <= NEARBY_RADIUS_KM * 1000"));
assert("Nearby discovery uses backend resource", discoveryResource.includes("/discovery/nearby") && home.includes("useNearbyPlacesQuery"));
assert("Frontend never calls Foursquare directly", !home.includes("places-api.foursquare.com") && !discoveryResource.includes("foursquare.com"));
assert("External discovery places have a safe preview", home.includes("ExternalPlaceSheet") && home.includes("selectedExternal"));
assert("External place sheet is an overlay above the tab bar", externalPlaceSheet.includes("MAIN_TAB_BAR_HEIGHT") && externalPlaceSheet.includes("bottom: MAIN_TAB_BAR_HEIGHT") && externalPlaceSheet.includes("position: \"absolute\""));
assert("External places use real coordinates", realMapWeb.includes("externalPlaces") && realMapWeb.includes("place.latitude") && realMapWeb.includes("place.longitude"));
assert("Home map has no fake cluster", !home.includes('clusterCount') && !home.includes("const slots"));
assert("Home nearby cards use real entity ids", home.includes("venuesQuery.data?.items") && home.includes("eventsQuery.data?.items") && home.includes('pathname: "/venue/[id]"') && home.includes('pathname: "/event/[id]"'));
assert("Home discovery search and filters are present", home.includes("FigmaHomeSearch") && home.includes("FigmaHomeFilters") && home.includes("query.trim().toLowerCase()"));
assert("GroupDetail imports social resources", groupDetail.includes("resources/groups") && groupDetail.includes("resources/friends") && groupDetail.includes("resources/invites"));
assert("InviteToGroup avoids legacy stores", !inviteToGroup.includes("useGroupStore") && !inviteToGroup.includes("useInviteStore"));
assert("InviteToGroup imports resources", inviteToGroup.includes("resources/groups") && inviteToGroup.includes("resources/friends") && inviteToGroup.includes("resources/invites"));
assert("GroupChat uses query metadata and chat store", !groupChat.includes("useGroupStore") && groupChat.includes("resources/groups") && groupChat.includes("chat-store"));
assert("ChatInbox uses social resources", !chatInbox.includes("useGroupStore") && chatInbox.includes("resources/groups") && chatInbox.includes("resources/friends"));
assert("DirectChat avoids legacy friend loader", !directChat.includes("getFriends(") && directChat.includes("resources/friends"));
assert("ChatInbox uses messaging resource", chatInbox.includes("resources/messages") && !chatInbox.includes("getDirectMessages") && !chatInbox.includes("getGroupMessages"));
assert("DirectChat uses messaging resource", directChat.includes("resources/messages") && !directChat.includes("getDirectMessages"));
assert("GroupChat uses messaging resource", groupChat.includes("resources/messages") && !groupChat.includes("getGroupMessages"));
assert("messaging resource uses apiClient", messagesResource.includes("apiClient") && messagesResource.includes("apiClientWithMeta"));
assert("messaging query keys are defined", read("src/services/api/query-keys.ts").includes("messageKeys") && messagesResource.includes("messageKeys"));
assert("socket client is singleton", socketService.includes("let socket: AppSocket | null = null") && socketService.includes("socket = io(") && (socketService.match(/socket = io\(/g) ?? []).length === 1);
assert("socket message listeners expose cleanup", /currentSocket\.off\([\s\S]{0,80}?"message:new"/.test(socketService) && /currentSocket\.off\([\s\S]{0,100}?"direct:message:new"/.test(socketService));
assert("realtime message updates target React Query", groupChat.includes("queryClient.setQueryData") && directChat.includes("queryClient.setQueryData"));
assert("realtime dedupe uses message ids", groupChat.includes("item.id !== message.id") && directChat.includes("item.id !== message.id"));
assert("no socket token logging", !socketService.includes("console.log(accessToken") && !socketService.includes("console.log(token"));
assert("refresh is single-flight", apiClient.includes("let refreshFlight") && apiClient.includes("if (!refreshFlight)") && apiClient.includes("refreshFlight = null"));
assert("refreshed token reauthenticates socket", apiClient.includes("reauthenticateSocket(result.accessToken)") && socketService.includes("export function reauthenticateSocket"));
assert("socket reauth preserves singleton", socketService.includes("socket.auth") && socketService.includes("socket.disconnect()") && socketService.includes("socket.connect()") && (socketService.match(/socket = io\(/g) ?? []).length === 1);
assert("logout invalidates refresh generation", authService.includes("beginSessionTermination()") && apiClient.includes("generationAtStart !== sessionGeneration"));
assert("refresh retries only once", apiClient.includes("retryOnUnauthorized: false") && apiClient.includes("!isAuthEndpoint(path)"));
assert("notification center is shell overlay only", !fs.existsSync(path.join(root, "src/app/notification-center.tsx")) && !fs.existsSync(path.join(root, "src/app/(main)/notification-center.tsx")) && tabs.includes("NotificationCenterExperience"));
assert("explore opens notification center overlay", explore.includes("openNotificationCenter()") && explore.includes("Abrir notificações"));
assert("legacy invites route redirects to explore", invitesRoute.includes("/(main)/explore"));
assert("notification preferences remain separate", read("src/app/(main)/notifications.tsx").includes("FigmaNotificationsExperience") && notificationCenter.includes("useReceivedInvitesQuery"));assert("active Friends uses React Query resource", friends.includes("useFriendsQuery") && !friends.includes("getFriends"));
assert("CreateGroup has no group store authority", !createGroup.includes("useGroupStore"));
assert("Notification Center uses notifications resource", notificationCenter.includes("resources/notifications") && notificationCenter.includes("useNotificationsQuery") && notificationCenter.includes("useReceivedInvitesQuery") && !notificationCenter.includes("useNotificationStore"));
assert("Notification Center unread count is backend-backed", notificationCenter.includes("useUnreadNotificationCountQuery"));
assert("Notification Center read mutation is backend-backed", notificationCenter.includes("useMarkNotificationReadMutation"));
assert("push device resource uses apiClient", read("src/services/api/resources/push-devices.ts").includes("apiClient") && read("src/services/api/resources/push-devices.ts").includes("/notifications/devices"));
assert("push registration is native guarded", read("src/services/push-device-registration.native.ts").includes("getExpoPushTokenAsync") && read("src/services/push-device-registration.web.ts").includes("registerPushDeviceIfEnabled"));
assert("notification center has no notification store authority", !notificationCenter.includes("useNotificationStore") && !notificationCenter.includes("loadNotifications"));
assert("notification center has no demo data", !["Lara", "Mateus", "Mariana F.", "Ricardo A.", "Clos Lounge", "Primavera Sound SP"].some((token) => notificationCenter.includes(token)));
assert("imported FSQ occupancy requires real capacity", venueState.includes("occupancyPercent") && venueState.includes("Number.isFinite(percentage)") && venueState.includes("Movimento indisponível"));
assert("imported FSQ availability is neutral", venueState.includes('venue.externalProvider === "FSQ_OS"') && venueState.includes("Horário indisponível"));
assert("manual occupancy labels remain available", venueState.includes("Cheio") && venueState.includes("Movimentado") && venueState.includes("Tranquilo"));
assert("occupancy uses API percent directly", venueState.includes("Number(venue.occupancyPercent)") && !venueState.includes("venue.occupancy)"));
assert("zero percent is known", venueState.includes("Number.isFinite(percentage)") && venueState.includes("percentage > 70"));
assert("over-capacity percent is preserved", venueState.includes("percentage }"));
assert("ChatInbox uses aggregated inbox query", chatInbox.includes("useChatInboxQuery") && chatInbox.includes("/messages/inbox") === false);
assert("ChatInbox does not fan out message history", !chatInbox.includes("useQueries") && !chatInbox.includes("listDirectMessages") && !chatInbox.includes("listGroupMessages"));
assert("messaging resource exposes unread count", messagesResource.includes("useChatUnreadCountQuery") && messagesResource.includes("/messages/unread/count"));
assert("messaging resource exposes mark-read", messagesResource.includes("useMarkChatReadMutation") && messagesResource.includes("/messages/read"));
assert("DirectChat marks direct thread read via API", directChat.includes("useMarkChatReadMutation") && directChat.includes('threadType: "DIRECT"'));
assert("GroupChat marks group thread read via API", groupChat.includes("useMarkChatReadMutation") && groupChat.includes('threadType: "GROUP"'));
assert("read state is not local unread authority", !chatInbox.includes("setUnread") && !directChat.includes("setUnread") && !groupChat.includes("setUnread"));
assert("message query keys include inbox and unread", read("src/services/api/query-keys.ts").includes("inbox:") && read("src/services/api/query-keys.ts").includes("unreadCount"));
assert("direct typing uses socket with cleanup", directChat.includes("emitDirectTyping") && directChat.includes("onDirectTyping") && directChat.includes("clearTimeout"));
assert("group typing uses socket with cleanup", groupChat.includes("emitGroupTyping") && groupChat.includes("onGroupTyping") && groupChat.includes("clearTimeout"));
assert("direct read state is backend backed", directChat.includes("useDirectReadStateQuery") && messagesResource.includes("/messages/read-state/direct/"));
assert("direct read event updates React Query", directChat.includes("onDirectRead") && directChat.includes("messageKeys.directReadState"));
assert("no delivered receipt state", !directChat.includes("Entregue") && !directChat.includes("delivered"));
assert("typing has stale expiry", directChat.includes("4000") && groupChat.includes("4000"));
assert("message lifecycle mutations use resource", messagesResource.includes("useEditDirectMessageMutation") && messagesResource.includes("useDeleteDirectMessageMutation") && messagesResource.includes("useEditGroupMessageMutation") && messagesResource.includes("useDeleteGroupMessageMutation"));
assert("delete confirmation is web safe and native confirmed", confirmDelete.includes("window.confirm") && confirmDelete.includes("Alert.alert") && directChat.includes("confirmDelete") && groupChat.includes("confirmDelete"));
assert("delete remains gated by confirmation", directChat.includes("confirmDelete(() =>") && directChat.includes("deleteMutation.mutateAsync({ messageId })") && groupChat.includes("confirmDelete(() =>") && groupChat.includes("deleteMutation.mutateAsync({ groupId, messageId })"));
assert("message actions are contextual, not inline", contextActions.includes("onLongPress") && contextActions.includes("contextmenu") && !directChat.includes("styles.messageActions") && !groupChat.includes("styles.messageActions"));
assert("context target owns bubble width constraint", contextActions.includes('maxWidth: "75%"') && directChat.includes('maxWidth: "100%"') && groupChat.includes('maxWidth: "100%"'));
assert("deleted messages have no lifecycle actions", directChat.includes("enabled={!item.deletedAt}") && groupChat.includes("enabled={!item.deletedAt}") && contextActions.includes("own ?"));
assert("deleted context menu state is cleared", directChat.includes("if (activeContextMessageId === message.id)") && groupChat.includes("if (activeContextMessageId === message.id)"));
assert("context menu supports escape cleanup", contextActions.includes("onCancel") && directChat.includes("onCancel={closeContextMenu}") && groupChat.includes("onCancel={closeContextMenu}"));
assert("single edit mode is composer-level", directChat.includes("editingId") && groupChat.includes("editingId") && directChat.includes("editBar") && groupChat.includes("editBar") && directChat.includes("setEditingId(null)") && groupChat.includes("setEditingId(null)"));
assert("edit mode suppresses typing", directChat.includes("!friendId || editingId") && groupChat.includes("!groupId || editingId"));
assert("delete clears active edit target", directChat.includes("if (editingId === messageId)") && groupChat.includes("if (editingId === messageId)") && directChat.includes("if (editingId === message.id)") && groupChat.includes("if (editingId === message.id)"));
assert("single global message menu per chat", (directChat.match(/<MessageActionMenu/g) || []).length === 1 && (groupChat.match(/<MessageActionMenu/g) || []).length === 1 && !contextActions.includes("useState"));
assert("context menu is outside message map", directChat.indexOf("<MessageActionMenu") > directChat.lastIndexOf("</FlatList>") && groupChat.indexOf("<MessageActionMenu") > groupChat.lastIndexOf("</FlatList>"));
assert("outside click closes menu with cleanup", contextActions.includes("pointerdown") && contextActions.includes("menu.contains") && contextActions.includes("removeEventListener(\"pointerdown\""));
assert("outside click does not cancel edit mode", directChat.includes("onCancel={closeContextMenu}") && groupChat.includes("onCancel={closeContextMenu}") && !contextActions.includes("setEditing"));
assert("socket lifecycle events update cache by id", directChat.includes("onDirectMessageUpdated") && directChat.includes("onDirectMessageDeleted") && groupChat.includes("onMessageUpdated") && groupChat.includes("onMessageDeleted"));
assert("deleted messages render safe placeholder", directChat.includes("Mensagem excluída") && groupChat.includes("Mensagem excluída"));
assert("message lifecycle schema fields exist", messagesResource.includes("editedAt") && messagesResource.includes("deletedAt"));
assert("fixed ReactionType mapping", messagesResource.includes('REACTION_TYPES') && messagesResource.includes('type ReactionType'));
assert("reaction resources use apiClient", messagesResource.includes('setDirectMessageReaction') && messagesResource.includes('setGroupMessageReaction') && messagesResource.includes('method: "PUT"'));
assert("reaction context supports peers", contextActions.includes('reaction') && directChat.includes('enabled={!item.deletedAt}') && groupChat.includes('enabled={!item.deletedAt}'));
assert("reactions do not affect unread or inbox", !messagesResource.includes('invalidateQueries({ queryKey: messageKeys.unreadCount })') || messagesResource.includes('useSetDirectMessageReactionMutation'));
assert("deleted messages hide reactions", directChat.includes('!item.deletedAt && item.reactions') && groupChat.includes('!item.deletedAt && item.reactions'));
assert("reaction pills do not expose user lists", !messagesResource.includes('reactedBy') && !messagesResource.includes('userIds'));
assert("context menu uses safe viewport clamping", contextActions.includes("SAFE_MARGIN") && contextActions.includes("window.innerWidth") && contextActions.includes("window.innerHeight") && contextActions.includes("clampMenuPosition"));
assert("context menu remains a single overlay", contextActions.includes('position: "absolute"') && directChat.includes("activeContextMessageId ? <MessageActionMenu") && groupChat.includes("activeContextMessageId ? <MessageActionMenu"));
assert("reply action is global and available to peers", contextActions.includes('onReply') && contextActions.includes('Responder') && directChat.includes('onReply={selectReplyMessage}') && groupChat.includes('onReply={selectReplyMessage}'));
assert("reply create resource accepts replyToId", messagesResource.includes('replyToId?: string') && directChat.includes('replyToId: replyingToId') && groupChat.includes('replyToId: replyingToId'));
assert("single reply state and composer banner", directChat.includes('replyingToId') && groupChat.includes('replyingToId') && directChat.includes('Respondendo a') && groupChat.includes('Respondendo a'));
assert("reply and edit are mutually exclusive", directChat.includes('setReplyingToId(null)') && groupChat.includes('setReplyingToId(null)') && directChat.includes('setEditingId(null)') && groupChat.includes('setEditingId(null)'));
assert("reply quote is one level and deleted-safe", messagesResource.includes('replyTo?: ReplyPreview') && directChat.includes('item.replyTo.text') && groupChat.includes('item.replyTo.text'));
assert("forward resources use destination ids", messagesResource.includes("forwardDirectMessageResource") && messagesResource.includes("forwardGroupMessageResource") && messagesResource.includes("targetType") && messagesResource.includes("targetId"));
assert("forward resource never trusts copied text", !messagesResource.includes("isForwarded: true") && !messagesResource.includes("forwardedText"));
assert("forwarded message type is explicit", messagesResource.includes("isForwarded?: boolean"));
assert("context menu exposes Forward", contextActions.includes("Encaminhar mensagem") && contextActions.includes("onForward"));
assert("forward picker offers friends and groups", read("src/features/chat/ForwardPicker.tsx").includes("targetType: \"DIRECT\"") && read("src/features/chat/ForwardPicker.tsx").includes("targetType: \"GROUP\""));
assert("forward picker is used by both chats", directChat.includes("<ForwardPicker") && groupChat.includes("<ForwardPicker"));
assert("forwarded label hides source metadata", directChat.includes("↪ Encaminhada") && groupChat.includes("↪ Encaminhada") && !messagesResource.includes("sourceMessageId"));

assert("message types expose imageUrl", messagesResource.includes("imageUrl: string | null") && messagesResource.includes("ReplyPreview") && messagesResource.includes("lastMessage: { id: string; text: string; imageUrl"));
assert("image resources use apiClient multipart", messagesResource.includes("sendDirectImageMessageResource") && messagesResource.includes("sendGroupImageMessageResource") && messagesResource.includes("new FormData()") && messagesResource.includes('form.append("image"'));
assert("DirectChat has image picker and upload", directChat.includes('expo-image-picker') && directChat.includes("launchImageLibraryAsync") && directChat.includes("useSendDirectImageMessageMutation"));
assert("GroupChat has image picker and upload", groupChat.includes('expo-image-picker') && groupChat.includes("launchImageLibraryAsync") && groupChat.includes("useSendGroupImageMessageMutation"));
assert("image messages render in both chats", directChat.includes('item.imageUrl && !item.deletedAt') && groupChat.includes('item.imageUrl && !item.deletedAt') && directChat.includes('Imagem da mensagem') && groupChat.includes('Imagem da mensagem'));
assert("image messages do not offer Forward", directChat.includes("canForward={!Boolean(messages.find") && groupChat.includes("canForward={!Boolean(messages.find") && contextActions.includes("canForward"));
assert("image-only bubbles have no fake text", directChat.includes("!selectedImage") && groupChat.includes("!selectedImage") && messagesResource.includes('text: string | null'));
assert("deleted messages hide imageUrl", directChat.includes('item.imageUrl && !item.deletedAt') && groupChat.includes('item.imageUrl && !item.deletedAt'));
assert("image reply visual exists", directChat.includes("replyTo.imageUrl") && groupChat.includes("replyTo.imageUrl") && messagesResource.includes("imageUrl?: string | null"));
assert("message media URLs use backend resolver", directChat.includes("resolveBackendMediaUrl(item.imageUrl)") && groupChat.includes("resolveBackendMediaUrl(item.imageUrl)") && directChat.includes("resolveBackendMediaUrl(item.replyTo.imageUrl)") && groupChat.includes("resolveBackendMediaUrl(item.replyTo.imageUrl)"));
assert("image upload avoids base64 and custom socket events", !messagesResource.includes("base64") && !directChat.includes("direct:image:new") && !groupChat.includes("group:image:new"));
assert("multipart image resources accept replyToId", messagesResource.includes("imageFormData(asset, text, replyToId)") && messagesResource.includes('form.append("replyToId", replyToId)'));
assert("Direct image send forwards replyingToId", directChat.includes("imageSendMutation.mutateAsync({ userId: friendId, asset: selectedImage, text: trimmedText, replyToId: replyingToId ?? undefined })"));
assert("Group image send forwards replyingToId", groupChat.includes("imageSendMutation.mutateAsync({ groupId, asset: selectedImage, text: trimmed, replyToId: replyingToId ?? undefined })"));
assert("image replies are not blocked", !directChat.includes("Respostas com imagem ainda não são suportadas") && !groupChat.includes("Respostas com imagem ainda não são suportadas"));
assert("image-only send is enabled in both chats", directChat.includes("(!text.trim() && !selectedImage) || sending") && groupChat.includes("(!text.trim() && !selectedImage) || sending") && directChat.includes("text: trimmedText") && groupChat.includes("text: trimmed"));
assert("single image viewer is global per chat", (directChat.match(/<MessageImageViewer/g) || []).length === 1 && (groupChat.match(/<MessageImageViewer/g) || []).length === 1 && directChat.includes("viewerImageUrl") && groupChat.includes("viewerImageUrl"));
assert("message and quote images open viewer without nested buttons", directChat.includes("onStartShouldSetResponder={() => true}") && groupChat.includes("onStartShouldSetResponder={() => true}") && directChat.includes("onTouchEnd={() => setViewerImageUrl") && groupChat.includes("onTouchEnd={() => setViewerImageUrl") && !directChat.includes("<Pressable onPress={() => setViewerImageUrl") && !groupChat.includes("<Pressable onPress={() => setViewerImageUrl"));
assert("image viewer supports backdrop close and web escape", read("src/features/chat/MessageImageViewer.tsx").includes("StyleSheet.absoluteFill") && read("src/features/chat/MessageImageViewer.tsx").includes("Escape") && read("src/features/chat/MessageImageViewer.tsx").includes("onRequestClose"));
assert("image viewer backdrop is independent from content", read("src/features/chat/MessageImageViewer.tsx").includes("onPress={onClose}") && read("src/features/chat/MessageImageViewer.tsx").includes('pointerEvents="box-none"'));
const composerIsFinal = (source) => source.includes('composerRow: { alignItems: "center", flexDirection: "row", gap: 8 }') && source.includes('composer: {') && source.includes('minHeight: 36') && source.includes('input: {') && source.includes('maxHeight: 110') && source.includes('inputContainer: { flex: 1, minWidth: 0 }');
const attachIsFinal = (source) => source.includes('style={styles.attachButton}') && source.includes('hitSlop={10}') && source.includes('attachButton: { alignItems: "center", alignSelf: "center", height: 24') && source.includes('width: 24') && source.indexOf('style={styles.attachButton}') < source.indexOf('<View style={styles.composer}>');
assert("composer sizing remains bounded", composerIsFinal(directChat) && composerIsFinal(groupChat) && directChat.includes("styles.imagePreview") && groupChat.includes("styles.imagePreview"));
assert("composer attach control fits final row", attachIsFinal(directChat) && attachIsFinal(groupChat));

for (const token of ["Clos Lounge", "Primavera Sound SP", "Lara", "Mateus", "Mariana F.", "Ricardo A.", "Parcels", "LCD Soundsystem"]) {
  const runtime = ["src/features", "src/components", "src/services", "src/store"]
    .flatMap((dir) => { const abs = path.join(root, dir); return fs.existsSync(abs) ? walk(abs) : []; })
    .filter((file) => /\.(tsx?|jsx?)$/.test(file) && !file.includes("figma-home-reference"))
    .some((file) => fs.readFileSync(file, "utf8").includes(token));
  assert(`no runtime demo: ${token}`, !runtime);
}

const failed = checks.filter((check) => !check.ok);
for (const check of checks) console.log(`${check.ok ? "PASS" : "FAIL"} ${check.name}`);
if (failed.length) process.exitCode = 1;
else console.log(`\n${checks.length} regression checks passed.`);

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const file = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(file) : [file];
  });
}
