import { Ionicons } from "@expo/vector-icons";
import { useRouter } from "expo-router";
import { Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { MAIN_TAB_BAR_HEIGHT } from "@/features/navigation/tabBarMetrics";
import { colors, fonts } from "@/theme/tokens";

const themes = [
  { label: "Escuro", description: "Sempre escuro", colors: ["#0B0D0F", "#15191D", "#F5C542"], enabled: true },
  { label: "Claro", description: "Sempre claro", colors: ["#F5F5F0", "#FFFFFF", "#1A1A2E"], enabled: false },
  { label: "Automático", description: "Segue o sistema", colors: ["#0B0D0F", "#F5F5F0", "#F5C542"], enabled: false },
] as const;
const fontSizes = ["Pequeno", "Médio", "Grande", "Extra grande"] as const;
const mapStyles = ["Noturno", "Standard", "Satélite"] as const;

export default function FigmaAppearanceExperience() {
  const router = useRouter();
  return <View style={styles.root}><Header onBack={() => router.replace("/(main)/profile")} /><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
    <Section title="Tema" />
    <View style={styles.themeRow}>{themes.map((theme) => <View key={theme.label} style={styles.themeOption}><View style={[styles.preview, !theme.enabled && styles.disabledPreview, theme.enabled && styles.activePreview]}>{theme.colors.map((color, index) => <View key={`${theme.label}-${color}`} style={[styles.previewColor, { backgroundColor: color, width: index === 2 ? 8 : undefined }]} />)}</View><Text style={[styles.themeLabel, !theme.enabled && styles.disabledText]}>{theme.label}</Text>{!theme.enabled ? <Text style={styles.coming}>Em breve</Text> : null}</View>)}</View>
    <Section title="Tamanho de texto" />
    <View style={styles.fontRow}>{fontSizes.map((size) => <Pressable key={size} disabled={size !== "Médio"} style={[styles.fontChoice, size === "Médio" && styles.fontActive, size !== "Médio" && styles.disabledChoice]}><Text style={[styles.fontChoiceText, size === "Médio" && styles.activeText, size !== "Médio" && styles.disabledText]}>{size === "Pequeno" ? "P" : size === "Médio" ? "M" : size === "Grande" ? "G" : "XG"}</Text></Pressable>)}</View><Text style={styles.example}>Exemplo: <Text style={styles.exampleStrong}>Auditório Ibirapuera</Text></Text>
    <Section title="Mapa" /><DisabledSelect label="Estilo do mapa" value="Noturno" options={mapStyles} />
    <Section title="Interface" /><DisabledToggle label="Emojis nos marcadores" sub="Mostra emojis nos pins do mapa" value /><DisabledToggle label="Animações" sub="Transições e efeitos visuais" value /><DisabledToggle label="Cards compactos" sub="Lista mais densa, menos espaço" value={false} />
    <Pressable onPress={() => router.replace("/(main)/profile")} style={styles.apply}><Text style={styles.applyText}>Aplicar</Text></Pressable>
  </ScrollView></View>;
}
function Header({ onBack }: { onBack: () => void }) { return <View style={styles.header}><Pressable onPress={onBack} hitSlop={8} accessibilityRole="button"><Ionicons name="arrow-back" size={20} color={colors.brand} /></Pressable><Text style={styles.title}>Aparência</Text></View>; }
function Section({ title }: { title: string }) { return <Text style={styles.section}>{title.toUpperCase()}</Text>; }
function DisabledSelect({ label, value, options }: { label: string; value: string; options: readonly string[] }) { return <View style={styles.select}><Text style={styles.label}>{label}</Text><View style={styles.selectValue}><Text style={styles.value}>{value}</Text><Ionicons name="chevron-down" size={14} color={colors.textMuted} /></View><Text style={styles.coming}>Em breve</Text></View>; }
function DisabledToggle({ label, sub, value }: { label: string; sub: string; value: boolean }) { return <View style={styles.toggleRow}><View style={styles.copy}><Text style={styles.label}>{label}</Text><Text style={styles.sub}>{sub}</Text><Text style={styles.coming}>Em breve</Text></View><View style={[styles.toggle, { backgroundColor: value ? colors.brand : "#2A3340" }, styles.disabledChoice]}><View style={[styles.knob, { left: value ? 23 : 3, backgroundColor: value ? colors.background : colors.textMuted }]} /></View></View>; }
const styles = StyleSheet.create({ root: { flex: 1, backgroundColor: colors.background }, header: { paddingTop: 14, paddingHorizontal: 20, paddingBottom: 12, flexDirection: "row", alignItems: "center", gap: 12, borderBottomWidth: 1, borderBottomColor: "rgba(248,250,252,0.06)" }, title: { color: colors.text, fontFamily: fonts.display, fontSize: 18, fontWeight: "700" }, content: { paddingHorizontal: 20, paddingBottom: MAIN_TAB_BAR_HEIGHT + 24 }, section: { marginTop: 20, marginBottom: 8, color: colors.textMuted, fontFamily: fonts.semibold, fontSize: 11, letterSpacing: 1.1 }, themeRow: { flexDirection: "row", gap: 10 }, themeOption: { flex: 1, alignItems: "center" }, preview: { height: 56, width: "100%", borderRadius: 12, overflow: "hidden", flexDirection: "row", marginBottom: 8 }, activePreview: { borderWidth: 2, borderColor: colors.brand }, disabledPreview: { opacity: 0.5 }, previewColor: { flex: 1 }, themeLabel: { color: colors.brand, fontSize: 12, fontFamily: fonts.semibold }, fontRow: { flexDirection: "row", gap: 8 }, fontChoice: { flex: 1, height: 38, borderRadius: 10, borderWidth: 1.5, borderColor: colors.border, alignItems: "center", justifyContent: "center" }, fontActive: { borderColor: colors.brand, backgroundColor: colors.brandSoft }, disabledChoice: { opacity: 0.5 }, fontChoiceText: { color: colors.textMuted, fontSize: 11 }, activeText: { color: colors.brand, fontFamily: fonts.bold }, disabledText: { color: colors.textMuted }, example: { color: colors.textMuted, fontSize: 12, marginTop: 6 }, exampleStrong: { color: colors.text, fontSize: 14 }, select: { minHeight: 58, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: "rgba(248,250,252,0.04)", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 8 }, label: { color: colors.text, fontFamily: fonts.medium, fontSize: 15, fontWeight: "500" }, selectValue: { flexDirection: "row", alignItems: "center", gap: 6 }, value: { color: colors.brand, fontSize: 13 }, coming: { color: colors.textMuted, fontSize: 11, marginTop: 3 }, toggleRow: { minHeight: 76, paddingVertical: 15, borderBottomWidth: 1, borderBottomColor: "rgba(248,250,252,0.04)", flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: 16 }, copy: { flex: 1 }, sub: { color: colors.textMuted, fontSize: 12, lineHeight: 17, marginTop: 2 }, toggle: { width: 46, height: 26, borderRadius: 13 }, knob: { position: "absolute", top: 3, width: 20, height: 20, borderRadius: 10 }, apply: { height: 50, borderRadius: 14, backgroundColor: colors.brand, alignItems: "center", justifyContent: "center", marginTop: 24 }, applyText: { color: colors.background, fontFamily: fonts.bold, fontSize: 15 } });
