import { Ionicons } from "@expo/vector-icons";
import { LinearGradient } from "expo-linear-gradient";
import { router } from "expo-router";
import { useMemo, useState } from "react";
import { ActivityIndicator, Image, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { type ApiEvent } from "@/services/api";
import { useEventsQuery } from "@/services/api/resources/events";
import { colors, fonts, radii } from "@/theme/tokens";

const DATE_TABS = ["Agora", "Hoje", "Amanhã", "Fim de sem."] as const;
const GENRES = ["Todos", "Show", "Festival", "Balada", "Jazz", "Cinema"] as const;
type DateTab = (typeof DATE_TABS)[number];
const genreAliases: Record<string, string[]> = { Show: ["show", "musica", "concerto"], Festival: ["festival", "evento"], Balada: ["balada", "festa", "club"], Jazz: ["jazz"], Cinema: ["cinema", "filme"] };

export default function EventsExperience() {
  const eventsQuery = useEventsQuery();
  const events = eventsQuery.data?.items ?? [];
  const [dateTab, setDateTab] = useState<DateTab>("Agora"); const [genre, setGenre] = useState("Todos");
  const loading = eventsQuery.isLoading; const error = eventsQuery.error ? "Não foi possível carregar os eventos." : null;
  const load = () => { void eventsQuery.refetch(); };
  const filtered = useMemo(() => events.filter((event) => !isPast(event) && matchesDate(event, dateTab) && matchesGenre(event.category, genre)).sort(sortEvents), [events, dateTab, genre]);
  return <View style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><Text style={styles.heading}>Eventos</Text><View style={styles.dateControl}>{DATE_TABS.map((tab) => <Pressable key={tab} onPress={() => setDateTab(tab)} style={[styles.dateTab, dateTab === tab && styles.dateTabActive]}><Text style={[styles.dateText, dateTab === tab && styles.dateTextActive]}>{tab}</Text></Pressable>)}</View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.genreRow}>{GENRES.map((item) => <Pressable key={item} onPress={() => setGenre(item)} style={[styles.genreChip, genre === item && styles.genreChipActive]}><Text style={[styles.genreText, genre === item && styles.genreTextActive]}>{item}</Text></Pressable>)}</ScrollView>{loading ? <View style={styles.state}><ActivityIndicator color={colors.brand} /><Text style={styles.muted}>Carregando eventos…</Text></View> : error ? <Pressable onPress={() => void load()} style={styles.state}><Ionicons color={colors.brand} name="refresh-outline" size={22} /><Text style={styles.muted}>{error} Toque para tentar novamente.</Text></Pressable> : filtered.length === 0 ? <View style={styles.empty}><Ionicons color={colors.brand} name="calendar-outline" size={30} /><Text style={styles.emptyTitle}>Nenhum evento encontrado</Text><Text style={styles.muted}>Tente outra data ou categoria.</Text></View> : <View style={styles.list}>{filtered.map((event) => <EventCard key={event.id} event={event} />)}</View>}</ScrollView></View>;
}

function EventCard({ event }: { event: ApiEvent }) { const price = event.price == null || event.price === "" ? null : Number(event.price) > 0 ? `R$ ${Number(event.price).toFixed(0)}` : "Gratuito"; const time = normalizeEventTime(event.time); return <Pressable onPress={() => router.push({ pathname: "/event/[id]", params: { id: event.id } })} style={({ pressed }) => [styles.card, pressed && styles.pressed]}><View style={styles.cardImage}>{event.image ? <Image source={{ uri: event.image }} style={styles.image} /> : <View style={styles.placeholder}><Ionicons name="calendar-outline" size={28} color={colors.brand} /></View>}<LinearGradient colors={["rgba(21,25,29,1)", "transparent"]} start={{ x: 0.5, y: 1 }} end={{ x: 0.5, y: 0.35 }} style={styles.imageGradient} /><View style={styles.categoryBadge}><Text style={styles.categoryText}>{event.category.toUpperCase()}</Text></View></View><View style={styles.cardInfo}><Text numberOfLines={2} style={styles.title}>{event.title}</Text><Text numberOfLines={1} style={styles.venue}>{event.venueName ?? event.venue?.name ?? "Local não informado"}</Text><View style={styles.metaRow}><View style={styles.metaItem}><Ionicons name="calendar-outline" size={13} color={colors.textSecondary} /><Text style={styles.metaText}>{formatEventDate(event)}</Text></View>{time && <View style={styles.metaItem}><Ionicons name="time-outline" size={13} color={colors.textSecondary} /><Text style={styles.metaText}>{time}</Text></View>}{price && <Text style={[styles.price, price === "Gratuito" && styles.free]}>{price}</Text>}</View></View></Pressable>; }
function parseEventStart(event: ApiEvent) { const raw = event.date.trim(); const parsed = new Date(raw.includes("T") ? raw : `${raw}T${event.time || "00:00"}`); return Number.isNaN(parsed.getTime()) ? null : parsed; }
function formatEventDate(event: ApiEvent) { const date = parseEventStart(event); if (!date) return event.date; const now = new Date(); const tomorrow = new Date(now); tomorrow.setDate(now.getDate() + 1); return date.toDateString() === now.toDateString() ? "Hoje" : date.toDateString() === tomorrow.toDateString() ? "Amanhã" : date.toLocaleDateString("pt-BR", { weekday: "short", day: "numeric", month: "short" }).replace(/\.$/, ""); }
function normalizeEventTime(value: string | null | undefined) { const raw = value?.trim() ?? ""; if (!raw || /^(agora|ao vivo|live)$/i.test(raw)) return null; const match = raw.match(/^(\d{1,2})(?::|h)(\d{2})?$/i); if (!match) return raw; return `${match[1]}h${match[2] ?? ""}`; }
function matchesDate(event: ApiEvent, tab: DateTab) { if (tab === "Agora") return event.isLive; const date = parseEventStart(event); if (!date) return false; const now = new Date(); if (tab === "Hoje") return date.toDateString() === now.toDateString(); if (tab === "Amanhã") { const tomorrow = new Date(now); tomorrow.setDate(now.getDate() + 1); return date.toDateString() === tomorrow.toDateString(); } const day = date.getDay(); return day === 0 || day === 6; }
function matchesGenre(value: string, genre: string) { return genre === "Todos" || (genreAliases[genre]?.some((alias) => value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().includes(alias)) ?? false); }
function isPast(event: ApiEvent) { return !event.isLive && (parseEventStart(event)?.getTime() ?? Number.MAX_SAFE_INTEGER) < Date.now(); }
function sortEvents(a: ApiEvent, b: ApiEvent) { if (a.isLive !== b.isLive) return a.isLive ? -1 : 1; return (parseEventStart(a)?.getTime() ?? Number.MAX_SAFE_INTEGER) - (parseEventStart(b)?.getTime() ?? Number.MAX_SAFE_INTEGER); }

const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { paddingHorizontal: 20, paddingTop: 16, paddingBottom: 100 }, heading: { color: colors.text, fontFamily: fonts.display, fontSize: 22, fontWeight: "700", marginBottom: 16 }, dateControl: { backgroundColor: colors.surface, borderRadius: 14, padding: 4, flexDirection: "row", marginBottom: 14 }, dateTab: { flex: 1, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center" }, dateTabActive: { backgroundColor: colors.elevated }, dateText: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12 }, dateTextActive: { color: colors.text, fontFamily: fonts.semibold }, genreRow: { gap: 7, paddingBottom: 2, paddingRight: 16 }, genreChip: { height: 30, borderRadius: radii.pill, borderWidth: 1, borderColor: colors.border, paddingHorizontal: 12, justifyContent: "center" }, genreChipActive: { borderColor: colors.brand, backgroundColor: colors.brandSoft }, genreText: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12 }, genreTextActive: { color: colors.brand, fontFamily: fonts.semibold }, list: { paddingTop: 16, gap: 16 }, card: { borderRadius: 16, overflow: "hidden", backgroundColor: colors.surface, borderWidth: 1, borderColor: "rgba(248,250,252,.05)" }, cardImage: { height: 140, backgroundColor: colors.elevated, position: "relative" }, image: { width: "100%", height: "100%" }, placeholder: { flex: 1, alignItems: "center", justifyContent: "center" }, imageGradient: { position: "absolute", left: 0, right: 0, bottom: 0, height: 80 }, categoryBadge: { position: "absolute", top: 10, left: 12, borderRadius: 20, paddingVertical: 4, paddingHorizontal: 10, backgroundColor: "rgba(11,13,15,.7)" }, categoryText: { color: colors.success, fontFamily: fonts.bold, fontSize: 10, letterSpacing: 0.6 }, cardInfo: { paddingVertical: 12, paddingHorizontal: 14 }, title: { color: colors.text, fontFamily: fonts.bold, fontSize: 16, marginBottom: 3 }, venue: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 12, marginBottom: 10 }, metaRow: { flexDirection: "row", alignItems: "center", gap: 12 }, metaItem: { flexDirection: "row", alignItems: "center", gap: 5 }, metaText: { color: colors.textSecondary, fontFamily: fonts.regular, fontSize: 12 }, price: { marginLeft: "auto", color: colors.text, fontFamily: fonts.bold, fontSize: 13 }, free: { color: colors.success }, state: { alignItems: "center", justifyContent: "center", gap: 10, paddingVertical: 48 }, muted: { color: colors.textMuted, fontFamily: fonts.regular, fontSize: 13, textAlign: "center" }, empty: { alignItems: "center", paddingVertical: 54, gap: 10 }, emptyTitle: { color: colors.text, fontFamily: fonts.bold, fontSize: 16 }, pressed: { opacity: 0.8 } });
